Eigen: Port the eigen library into Nuttx
Add all test cases, including running error test cases
The cases that cannot be added to the compilation are as follows,
because Nuttx does not support the features:
jacobisvd,bdcsvd: Missing header file, Nuttx not available
boostmultiprec:   error: boost/serialization/nvp.hpp: No such file or directory   71 | #include <boost/serialization/nvp.hpp>
bug1213: /usr/bin/ld: nuttx.rel:(.rodata.g_builtins+0x3c): undefined reference to `bug1213_main',There is no main function in itself.
qtvector:        error:#include <QtCore/Qvector>
sycl_basic:      error:#include <CL/sycl.hpp>

Signed-off-by: wangmingrong <wangmingrong@xiaomi.com>